dj11/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.auth.views import LoginView, LogoutView

from menus.views import HomeView
from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view


urlpatterns = [
   url(r'^admin/', admin.site.urls),
   url(r'^$', HomeView.as_view(), name='home'),
   url(r'^register/$', RegisterView.as_view(), name ='register'),
   url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
   url(r'^login/$', LoginView.as_view(), name ='login'),
   url(r'^logout/$', LogoutView.as_view(), name ='logout'),
   url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),
   url(r'^u/', include('profiles.urls', namespace='profiles')),
   url(r'^items/', include('menus.urls', namespace='menus')),
   url(r'^restraunts/', include('restraunts.urls', namespace='restraunts')),
   url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
   url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
]

restraunts/urls.py
from django.conf.urls import url



from .views import (
	RestrauntListView,
	RestrauntDetailView,
 	RestrauntCreateView,
 	RestrauntUpdateView,
	)

urlpatterns = [
   url(r'^create/$', RestrauntCreateView.as_view(), name='create'),
   #url(r'^(?P<slug>[\w-]+)/edit/$', RestrauntUpdateView.as_view(), name='edit'),
   url(r'^(?P<slug>[\w-]+)/$', RestrauntUpdateView.as_view(), name='detail'),
   url(r'$', RestrauntListView.as_view(), name='list'),
]

restraunts/models.py
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save, post_save
from django.core.urlresolvers import reverse

from .utils import unique_slug_generator
from .validators import validate_category

User = settings.AUTH_USER_MODEL



class RestrauntLocationMangerQuerySet(models.query.QuerySet):
	def search(self, query):
		if query:
			query = query.strip()
			return self.filter(
					Q(name__icontains=query)|
					Q(location__iexact=query)|
					Q(location__icontains=query)|
					Q(category__icontains=query)|
					Q(category__iexact=query)|
					Q(item__name__icontains=query)|
					Q(item__contents__icontains=query)
					).distinct()
		return self

class RestrauntLocationManager(models.Manager):
	def get_queryset(self):
		return RestrauntLocationMangerQuerySet(self.model, using=self._db)

	def search(self, query):
		return self.get_queryset().search(query)

class RestrauntLocation(models.Model):
	owner               = models.ForeignKey(User)
	name 				= models.CharField(max_length=120)
	location 			= models.CharField(max_length=120, null=True, blank=True)
	category            = models.CharField(max_length=120, null=True, blank=True, validators=[validate_category])
	timestamp           = models.DateTimeField(auto_now_add=True)
	updated             = models.DateTimeField(auto_now=True)
	slug         		= models.SlugField(null=True, blank=True)
	# my_date_field 	= models.DateTimeField(auto_now=False, auto_now_add=False)

	objects = RestrauntLocationManager()


	def __str__(self):
		return self.name

	def get_absolute_url(self):
		#return f"/restraunts/{self.slug}"
		return reverse('restraunts:detail', kwargs={'slug': self.slug})	

	@property
	def title(self):
		return self.name
		


def rl_pre_save_receiver(sender, instance, *args, **kwargs):
	instance.category = instance.category.capitalize()
	if not instance.slug:
		instance.slug = unique_slug_generator(instance)


#def rl_post_save_receiver(sender, instance, created, *args, **kwargs):
#	print('saved')
#	print(instance.timestamp)


pre_save.connect(rl_pre_save_receiver, sender=RestrauntLocation)


#post_save.connect(rl_post_save_receiver, sender=RestrauntLocation)		

restraunts/forms.py
from django import forms

from .models import RestrauntLocation

from .validators import validate_category


class RestrauntCreateForm(forms.Form):
	name 				= forms.CharField()
	location 			= forms.CharField(required=False)
	category            = forms.CharField(required=False)


	def clean_name(self):
		name = self.cleaned_data.get("name")
		if name == "Hello":
			raise forms.ValidationError("Not a valid name")
		return name 	



class RestrauntLocationCreateForm(forms.ModelForm):
	#email                      = forms.EmailField()
	#category                    = forms.CharField(required=False, validators=[validate_category])
	class Meta:
		model = RestrauntLocation
		fields = [
			'name',
			'location',
			'category',
			'slug',


		]		


	def clean_name(self):
		name = self.cleaned_data.get("name")
		if name == "Hello":
			raise forms.ValidationError("Not a valid name")
		return name 	


	'''def clean_email(self):
		email = self.cleaned_data.get("email")
		if ".edu" in email:
			raise forms.ValidationError("We do not accept edu emails")
		return email	'''

restraunts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView
from.forms import RestrauntCreateForm, RestrauntLocationCreateForm
from .models import RestrauntLocation



class RestrauntListView(LoginRequiredMixin, ListView):
	def get_queryset(self):
		return	RestrauntLocation.objects.filter(owner=self.request.user)	
	

class RestrauntDetailView(LoginRequiredMixin, DetailView):
	def get_queryset(self):
		return	RestrauntLocation.objects.filter(owner=self.request.user)	

class RestrauntCreateView(LoginRequiredMixin, CreateView):
	form_class = RestrauntLocationCreateForm
	login_url = '/login/'
	template_name = 'form.html'
	#success_url = "/restraunts/"


	def form_valid(self, form):
		instance = form.save(commit=False)
		instance.owner = self.request.user
		return super(RestrauntCreateView, self).form_valid(form)

	def get_context_data(self, *args, **kwargs):
		context = super(RestrauntCreateView, self).get_context_data(*args, **kwargs)
		context['title'] = 'Add Restraunt'
		return context 


class RestrauntUpdateView(LoginRequiredMixin, UpdateView):
	form_class = RestrauntLocationCreateForm
	login_url = '/login/'
	template_name = 'restraunts/detail-update.html'
	#success_url = "/restraunts/"


	def get_context_data(self, *args, **kwargs):
		context = super(RestrauntUpdateView, self).get_context_data(*args, **kwargs)
		name = self.get_object().name
		context['title'] = f'Update Restraunt: {name}'
		return context 

	def get_queryset(self):
		return	RestrauntLocation.objects.filter(owner=self.request.user)

restraunts/templates/restraunts/detail-update.html
{% extends "base.html" %}

{% block head_title %}{{ form.instance.title }} | Restraunts | {{ block.super }}{% endblock head_title %}

{% block content %}

<h1>{{ form.instance.title }} <small> {{ form.instance.category }}</small></h1>
<p>{{ form.instance.location }}</p>
<p>{{ form.instance.timestamp }}, Updated {{ form.instance.updated|timesince }} ago</p>

<hr/>
<h3>Make Changes</h3>
{% include 'snippets/form-snippet.html' with form=form %}

{% endblock %}

restraunts/templates/restraunts/restrauntlocation_detail.html
{% extends "base.html" %}

{% block head_title %}Restraunts | {{ block.super }}{% endblock head_title %}

{% block content %}

<h1>{{ object.title }} <small> {{ object.category }}</small></h1>
<p>{{ object.location }}</p>
<p>{{ object.timestamp }}, Updated {{ object.updated|timesince }} ago</p>
{% endblock %}

restraunts/templates/restraunts/restrauntlocation_list.html
{% extends "base.html" %}

{% block head_title %}Restraunts | {{ block.super }}{% endblock head_title %}

{% block content %}

<h1>My Restraunts <small><a href='{% url "restraunts:create" %}'>Add</a></small></h1>

<ul>
{% for obj in object_list %}
	<li><a href='{{ obj.get_absolute_url }}'>{{ obj }}</a><br/>
	{{ obj.name }} {{ obj.location }} {{ obj.category }} {{ obj.timestamp }} {{ obj.updated }}</li>
{% empty %}
	<li><a href='{% url "restraunts:create" %}'>Add One</a></li>

{% endfor %}
</ul>

{% endblock %}

restraunts/templates/restraunts/restraunts_list.html
{% extends "base.html" %}

{% block head_title %}Restraunts | {{ block.super }}{% endblock head_title %}

{% block content %}

<h1>Restraunt List</h1>

<ul>
{% for obj in object_list %}
	<li>{{ obj }}<br/>
	{{ obj.name }} {{ obj.name }} {{ obj.category }} {{ obj.timestamp }} {{ obj.updated }}</li>
{% endfor %}
</ul>

{% endblock %}